@startuml
left to right direction
skinparam packageStyle rect

' Definição dos atores e hierarquia
actor "Usuário comum" as Usuario
actor "Expositor" as Expositor
actor "Participante" as Participante
actor "Organizador" as Organizador

Expositor --|> Usuario
Participante --|> Usuario
Organizador --|> Usuario


' Pacotes de casos de uso
package "SGFPO" {
    Usuario -- (Acessar sistema)
    (Recuperar senha)<.. (Acessar sistema) : <<extends>>
     Participante  -- (Acesso sem login)
  Expositor -- (Gerenciar perfil expositor) 
  Expositor -- (Gerenciar produtos)
  Expositor -- (Notificar estoque) 
  Expositor -- (Visualizar registro das vendas) 
  (Visualizar registro das vendas) <..(Registrar vendas manualmente): <<extends>>
  Expositor -- (Registrar vendas manualmente) 
  (Visualizar registro das vendas)  <..(Registrar vendas manualmente): <<includes>>
  Expositor -- (Notificar vendas on-line)  
  Participante -- (Visualizar histórico de compras)
  Participante -- (Filtrar produtos)
 Participante -- (Enviar mensagem ao expositor)
  Participante -- (Comprar produto com autenticação)
 Participante -- (Suporte técnico ao participante)
 Expositor -- (Suporte técnico ao expositor)
 Participante -- (Adicionar à lista de desejos)
 Usuario -- (Personalizar aparência da plataforma)
 Usuario -- (Comprar produto sem autenticação)
 Participante -- (Avaliar compra)
(Visualizar histórico de compras)  <..(Avaliar compra): <<includes>>
   Expositor -- (Oferecer descontos)
   Participante -- (Notificar descontos)
  Expositor -- (Realizar operações offline)
  Organizador -- (Visualizar relatórios)
}
@enduml