@startuml
left to right direction

actor "Participante" as Usuario

usecase "Avaliar compra" as UC1
usecase "Visualizar histórico de compras" as UC2

Usuario -- UC1

UC2 <.. UC1 : <<includes>>
@enduml