@startuml

:Participante acessa a barra de busca de produtos;
:Participante seleciona a opção de filtrar produtos;
:Sistema exibe campo de pesquisa e opções de filtro (Nome, Segmento e Preço);
fork
    :Participante insere termo de pesquisa;
fork again
    :Participante pesquisa por filtro;
end fork
if (Existem produtos que atendem aos critérios?) then (Sim)
    :Sistema exibe lista de produtos disponíveis;
    :Participante visualiza os detalhes de um produto;
else (Não)
    :Sistema exibe MSG17 ("Nenhum produto encontrado.");
endif
stop

@enduml