@startuml

start

:Participante acessa a seção "Histórico de Compras";
:Sistema exibe a lista de compras realizadas;

if (Existem compras registradas?) then (Sim)
    :Participante visualiza os detalhes de cada compra;
else (Não)
    :Sistema exibe MSG16 "Nenhuma compra registrada.";
endif

stop

@enduml