@startuml
start

:Buscar produtos comprados associados ao participante;
if (Produtos encontrados?) then (Sim)
  :Exibir lista de produtos comprados;
else (Não)
  :Exibir mensagem de lista vazia;
endif

stop
@enduml