@startuml
start

:Receber dados da venda;
:Validar informações;
if (Dados válidos?) then (Sim)
  :Registrar venda no sistema;
  :Exibir mensagem de sucesso;
else (Não)
  :Exibir mensagem de erro;
endif

stop
@enduml