@startuml

start

:Expositor acessa a seção "Vendas";
:Sistema exibe a lista de vendas realizadas;

if (Existem vendas registradas?) then (Sim)
    :Expositor visualiza a lista de transações;
else (Não)
    :Sistema exibe MSG13 "Nenhuma venda registrada.";
    if (Expositor deseja adicionar um registro manualmente?) then (Sim)
        :Expositor clica em "Inserir registro de venda";
        :Sistema exibe formulário para inserção;
        :Expositor insere os dados e confirma;
        :Sistema atualiza a listagem de vendas;
        else (Não)
        stop
    endif
endif

stop

@enduml