@startuml
start

:Solicitar listagem de produtos;
:Consultar banco de dados para obter lista de produtos;
if (Produtos encontrados?) then (Sim)
  :Exibir lista de produtos;
else (Não)
  :Exibir mensagem de lista vazia;
endif

stop
@enduml