@startuml
start

:Receber dados de novo perfil;
:Verificar permissões para alteração;
if (Permissão concedida?) then (Sim)
  :Atualizar dados de perfil;
  :Exibir mensagem de sucesso;
else (Não)
  :Exibir mensagem de erro;
endif
stop

@enduml
