@startuml
start

:Receber dados de novo perfil;
:Verificar dados válidos para alteração;
if (Dados válidos?) then (Sim)
  :Atualizar dados de perfil;
  :Exibir mensagem de sucesso;
else (Não)
  :Exibir mensagem de erro;
endif
stop

@enduml