@startuml
start

:Consultar banco de dados para obter transações;
if (Transações encontradas?) then (Sim)
  :Exibir lista de transações;
else (Não)
  :Exibir mensagem de lista vazia;
endif

stop
@enduml